asset: https://servicedesk.infn.it/secure/ObjectSchema.jspa?id=44&typeId=2441&mode=object&objectId=119372
autosync: false
charturl: https://baltig.infn.it/epics-containers/ioc-launcher-chart.git
devgroup: timing
devices:
  evr:
  - bus: 9
    func: 0
    iocinit:
    - name: Pul0-Width-SP
      value: '0'
    - name: Pul0-Delay-SP
      value: '0'
    - name: Pul0-Polarity-Sel
      value: '0'
    - name: Pul0-Ena-Sel
      value: '1'
    - name: FrontUnivOut0-Src-Pulse-SP
      value: Pulser 0
    - name: FrontUnivOut0-Ena-SP
      value: '1'
    - name: Pul1-Width-SP
      value: '0'
    - name: Pul1-Delay-SP
      value: '0'
    - name: Pul1-Polarity-Sel
      value: '0'
    - name: Pul1-Ena-Sel
      value: '1'
    - name: FrontUnivOut1-Src-Pulse-SP
      value: Pulser 1
    - name: FrontUnivOut1-Ena-SP
      value: '1'
    - name: Pul2-Width-SP
      value: '0'
    - name: Pul2-Delay-SP
      value: '0'
    - name: Pul2-Polarity-Sel
      value: '0'
    - name: Pul2-Ena-Sel
      value: '1'
    - name: FrontUnivOut2-Src-Pulse-SP
      value: Pulser 2
    - name: FrontUnivOut2-Ena-SP
      value: '1'
    - name: Pul3-Width-SP
      value: '0'
    - name: Pul3-Delay-SP
      value: '0'
    - name: Pul3-Polarity-Sel
      value: '0'
    - name: Pul3-Ena-Sel
      value: '1'
    - name: FrontUnivOut3-Src-Pulse-SP
      value: Pulser 3
    - name: FrontUnivOut3-Ena-SP
      value: '1'
    - name: Link-Clk-SP
      value: '62.08'
    - name: Ena-Sel
      value: Enabled
    name: EVR-BPMCAM
    slot: 9
  - bus: 9
    func: 0
    iocinit:
    - name: Pul0-Width-SP
      value: '0'
    - name: Pul0-Delay-SP
      value: '0'
    - name: Pul0-Polarity-Sel
      value: '0'
    - name: Pul0-Ena-Sel
      value: '1'
    - name: FrontUnivOut0-Src-Pulse-SP
      value: Pulser 0
    - name: FrontUnivOut0-Ena-SP
      value: '1'
    - name: Pul1-Width-SP
      value: '0'
    - name: Pul1-Delay-SP
      value: '0'
    - name: Pul1-Polarity-Sel
      value: '0'
    - name: Pul1-Ena-Sel
      value: '1'
    - name: FrontUnivOut1-Src-Pulse-SP
      value: Pulser 1
    - name: FrontUnivOut1-Ena-SP
      value: '1'
    - name: Pul2-Width-SP
      value: '0'
    - name: Pul2-Delay-SP
      value: '0'
    - name: Pul2-Polarity-Sel
      value: '0'
    - name: Pul2-Ena-Sel
      value: '1'
    - name: FrontUnivOut2-Src-Pulse-SP
      value: Pulser 2
    - name: FrontUnivOut2-Ena-SP
      value: '1'
    - name: Pul3-Width-SP
      value: '0'
    - name: Pul3-Delay-SP
      value: '0'
    - name: Pul3-Polarity-Sel
      value: '0'
    - name: Pul3-Ena-Sel
      value: '1'
    - name: FrontUnivOut3-Src-Pulse-SP
      value: Pulser 3
    - name: FrontUnivOut3-Ena-SP
      value: '1'
    - name: Link-Clk-SP
      value: '62.08'
    - name: Ena-Sel
      value: Enabled
    name: EVR-CAM
    slot: 10
  - bus: 9
    func: 0
    iocinit:
    - name: Pul0-Width-SP
      value: '0'
    - name: Pul0-Delay-SP
      value: '0'
    - name: Pul0-Polarity-Sel
      value: '0'
    - name: Pul0-Ena-Sel
      value: '1'
    - name: FrontUnivOut0-Src-Pulse-SP
      value: Pulser 0
    - name: FrontUnivOut0-Ena-SP
      value: '1'
    - name: Pul1-Width-SP
      value: '0'
    - name: Pul1-Delay-SP
      value: '0'
    - name: Pul1-Polarity-Sel
      value: '0'
    - name: Pul1-Ena-Sel
      value: '1'
    - name: FrontUnivOut1-Src-Pulse-SP
      value: Pulser 1
    - name: FrontUnivOut1-Ena-SP
      value: '1'
    - name: Pul2-Width-SP
      value: '0'
    - name: Pul2-Delay-SP
      value: '0'
    - name: Pul2-Polarity-Sel
      value: '0'
    - name: Pul2-Ena-Sel
      value: '1'
    - name: FrontUnivOut2-Src-Pulse-SP
      value: Pulser 2
    - name: FrontUnivOut2-Ena-SP
      value: '1'
    - name: Pul3-Width-SP
      value: '0'
    - name: Pul3-Delay-SP
      value: '0'
    - name: Pul3-Polarity-Sel
      value: '0'
    - name: Pul3-Ena-Sel
      value: '1'
    - name: FrontUnivOut3-Src-Pulse-SP
      value: Pulser 3
    - name: FrontUnivOut3-Ena-SP
      value: '1'
    - name: Link-Clk-SP
      value: '62.08'
    - name: Ena-Sel
      value: Enabled
    name: EVR-ADC
    slot: 11
devtype: evr230
exec: start.sh
host: 10.16.4.62
iocbin: ../bin/linux-x86_64/elinp-gp04-ioc17
iocdir: cosylabioc
iocfunc: elinp_gp04_ioc17
iocname: mrf-diag-delay
iocprefix: LEL:TIM
name: mrf-diag-delay
nfsMounts:
- mountPath: /nfs/data
  name: data
  opt: -o credentials=/etc/smbcredentials
  path: /data_epik8s/eli/data
  server: 192.168.197.157
  type: cifs
- mountPath: /nfs/autosave
  name: autosave
  opt: -o credentials=/etc/smbcredentials
  path: /data_epik8s/eli/autosave
  server: 192.168.197.157
  type: cifs
- mountPath: /nfs/config
  name: config
  opt: -o credentials=/etc/smbcredentials
  path: /data_epik8s/eli/config
  server: 192.168.197.157
  type: cifs
scpoptions: -O
ssh_options: -o HostKeyAlgorithms=ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
workdir: /opt/codac-4.1/apps/elinp-gp04-ioc17/epik8s-mrf
